package com.example.myapplication.screens

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.layout.widthIn
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.navigation.NavHostController
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.myapplication.repository.DataRepository


@Composable
fun FirstScreen(navController: NavHostController) {
    var text by remember {
        mutableStateOf("")
    }

    var isGenerated by remember {
        mutableStateOf(false)
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(100.dp),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        TextField(
            value = text,
            onValueChange = {
                text = it
            },
            label = {
                Text("Введите количество фильмов")
            }
        )


        Spacer(Modifier.height(16.dp))

        Button(

            onClick = {
                DataRepository.filmsList =
                    DataRepository.baseFilms.shuffled().take(text.toInt())
                isGenerated = true
            },
            enabled = text.toIntOrNull()?.let { it > 0} == true
        ) {
            Text("Сгенерировать")
        }

        Spacer(Modifier.height(16.dp))

        Button(
            onClick = {
                navController.navigate("second")
            },
            enabled = isGenerated
        ) {
            Text("Открыть список")
        }


    }
}